[kotlin] remove k1 specific dependency from intellij.kotlin.base.projectStructure
- use RUNTIME scope to prevent explicit usages; it's impossible to remove the dependency completely due to dependencies inside the compiler itself, like

```
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/codegen/state/KotlinTypeMapper
  at org.jetbrains.kotlin.fir.backend.jvm.FirJvmTypeMapper$Context.hasNothingInNonContravariantPosition(FirJvmTypeMapper.kt:127)
  at org.jetbrains.kotlin.fir.backend.jvm.FirJvmTypeMapper$Context.writeGenericType(FirJvmTypeMapper.kt:97)
  at org.jetbrains.kotlin.fir.backend.jvm.FirJvmTypeMapper$Context.writeGenericType(FirJvmTypeMapper.kt:76)
  at org.jetbrains.kotlin.types.AbstractTypeMapper.mapClassType(AbstractTypeMapper.kt:206)
  at org.jetbrains.kotlin.types.AbstractTypeMapper.mapType(AbstractTypeMapper.kt:89)
  at org.jetbrains.kotlin.types.AbstractTypeMapper.mapType(AbstractTypeMapper.kt:53)
  at org.jetbrains.kotlin.types.AbstractTypeMapper.mapType$default(AbstractTypeMapper.kt:47)
  at org.jetbrains.kotlin.fir.backend.jvm.FirJvmTypeMapper.mapType(FirJvmTypeMapper.kt:66)
  at org.jetbrains.kotlin.analysis.api.fir.components.KaFirJavaInteroperabilityComponent.asPsiTypeElement(KaFirJavaInteroperabilityComponent.kt:165)```

KTIJ-37535

GitOrigin-RevId: a1488d29d4dc89a4de6b0cd5300518e631801497